### ISSUE TITLE
Create an initiation packet for new members.

### ISSUE THREAD

**Issue by Cribstone** [Code4Maine/code4maine-ops#10] opened 2014-11-13 17:56 UTC
http://www.codeforamerica.org/brigade/tools has some useful docs for [Welcoming New Members](https://docs.google.com/document/d/1AuMsUqCZ1Em99NvQje1dCI2cD1C54dD711sbm6FgYhE/edit?usp=sharing) and [Projects for New Brigade members](https://docs.google.com/document/d/1wo_skwazuom_Zkp7AmCSjy5JD8Z5WYSbhr2IUmqWdQ0/edit?usp=sharing) but locally specific materials including links to the relevant communication channels, hangouts schedules, local contacts etc... should also be included.

**Comment by powellc** [comment] 2015-09-28 17:13
Working on this again after taking some times off. Updates can be found in 10-initiation-packet-docs

**Comment by powellc** [comment] 2015-09-28 17:15
Closing this as a duplicate of #28

**Closed by powellc** 2015-09-28 17:15 UTC
Labels: captain, community-manager, enhancement, help wanted, in progress, statewide
